#!/bin/bash
: Returns the version of Python libraries.
: <<DOCUMENTATIONXX
use like this: 
> ./show_version numpy
numpy==1.26.4
DOCUMENTATIONXX

python -c "from importlib.metadata import version; print(\"$1\" + '==' + version(\"$1\"))"
